import { DealPricing, NichePreset } from './dealTypes';

export const DEAL_PRICING: DealPricing = {
  core7Usd: 149,
  core7Inr: 11999,
  plus2Usd: 79,
  plus2Inr: 5999,
  reelVideoUsd: 119,
  reelVideoInr: 8999,
};

export const NICHE_PRESETS: NichePreset[] = [
  {
    id: 'frames',
    name: 'Custom Photos & Picture Frames',
    subtitle: 'High-margin personalized wall art & framing studios',
    description: 'A complete Amazon & Shopify 7+2+1 listing asset pack showing custom frames on real walls, sizing scales, beveled matting, and an unboxing video.',
    badge: 'Popular Niche',
    videoUrl: '/src/assets/portfolio-5.mp4',
    videoPoster: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    videoTitle: 'Frame Unboxing & Wall Mount In-Motion',
    videoDuration: '0:15',
    slots: [
      {
        id: 1,
        slotType: 'core',
        slotNumber: '1 of 7 (Main)',
        title: 'Pure White Amazon Hero',
        tagline: 'Amazon, Etsy & Google Shopping Compliant',
        badge: 'Crucial CTR',
        categoryPurpose: 'Main Search Click Magnet',
        imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['100% Pure White (#FFFFFF)', '85%+ Frame Fill Ratio', 'Soft Realistic Ground Shadow', 'Natural Oak Finish'],
      },
      {
        id: 2,
        slotType: 'core',
        slotNumber: '2 of 7 (Infographic)',
        title: 'Dimensions & Scale Guide',
        tagline: 'Prevents Customer Sizing Returns',
        badge: 'Conversion Booster',
        categoryPurpose: 'Dimension & Scale Clarifier',
        imageUrl: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['8x10, 12x16, 16x20, 24x36 Callouts', 'Inches & Metric Measurements', 'Scale Next to Modern Sofa', 'Mat Opening Dimensions'],
      },
      {
        id: 3,
        slotType: 'core',
        slotNumber: '3 of 7 (Infographic)',
        title: 'Materials & Craftsmanship',
        tagline: 'Explaining Premium Wood & Joinery',
        badge: 'Perceived Value',
        categoryPurpose: 'Quality Verification',
        imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['100% Solid American Oak', 'Precision 45° Miter Corners', 'Museum UV Shatterproof Acrylic', 'Archival Acid-Free Backing'],
      },
      {
        id: 4,
        slotType: 'core',
        slotNumber: '4 of 7 (Lifestyle)',
        title: 'Hero Living Room Lifestyle',
        tagline: 'Emotional Home Connection',
        badge: 'Aspirational',
        categoryPurpose: 'Primary In-Room Setting',
        imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Scandinavian Interior Aesthetic', 'Natural Sunlight Angle', 'Harmonious Color Grading', 'High-Res Print Clarity'],
      },
      {
        id: 5,
        slotType: 'core',
        slotNumber: '5 of 7 (Lifestyle)',
        title: 'Modern Study / Bedroom Setting',
        tagline: 'Alternative Everyday Placement',
        badge: 'Versatility',
        categoryPurpose: 'Secondary Room Placement',
        imageUrl: 'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Minimalist Desk / Shelf Setup', 'Cozy Warm Ambient Lighting', 'Shows Standing or Wall Hanging', 'Relatable Proportions'],
      },
      {
        id: 6,
        slotType: 'core',
        slotNumber: '6 of 7 (Macro Detail)',
        title: 'Beveled Matboard & Glass Detail',
        tagline: 'Macro Close-Up of Quality',
        badge: 'Craft Focus',
        categoryPurpose: 'Tactile Inspection',
        imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Beveled 45° White Mat Cut', 'Anti-Glare Glass Sheen', 'Wood Grain Texture Zoom', 'No Pixelation Guarantee'],
      },
      {
        id: 7,
        slotType: 'core',
        slotNumber: '7 of 7 (Packaging)',
        title: 'Safe Transit & Unboxing Packaging',
        tagline: 'Zero Transit Breakage Reassurance',
        badge: 'Confidence',
        categoryPurpose: 'Damage Doubt Elimination',
        imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Heavy-Duty Foam Corner Protectors', 'Recyclable Kraft Box Exterior', 'Bubble Layer Cushioning', 'Ready-to-Gift Presentation'],
      },
      {
        id: 8,
        slotType: 'plus2',
        slotNumber: '+1 of 2 (A+ Upgrade)',
        title: '60-Second Wall Installation Guide',
        tagline: 'Removes Hanging Frustration',
        badge: 'A+ Content',
        categoryPurpose: 'Friction Removal',
        imageUrl: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Step 1-2-3 Visual Diagram', 'Pre-Installed D-Rings & Wire', 'Wall Anchor & Mini Level Included', 'No Measuring Headaches'],
      },
      {
        id: 9,
        slotType: 'plus2',
        slotNumber: '+2 of 2 (A+ Upgrade)',
        title: 'Brand vs Cheap Generic Matrix',
        tagline: 'Justifies Premium Price Point',
        badge: 'A+ Content',
        categoryPurpose: 'Value Comparison Table',
        imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Real Oak vs Compressed Cardboard', 'Archival Ink vs Fading Print', 'UV Shielding vs Scratched Plastic', '10-Year Fade Resistance'],
      },
    ],
  },
  {
    id: 'hampers',
    name: 'Gifting Items & Hampers',
    subtitle: 'Festival gift boxes, luxury curated hampers & corporate kits',
    description: 'A 7+2+1 listing engine designed to maximize holiday hamper sales with itemized breakdown infographics, ribbon packaging, and an unboxing reel.',
    badge: 'Seasonal Goldmine',
    videoUrl: '/src/assets/portfolio-5.mp4',
    videoPoster: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
    videoTitle: 'Luxury Hamper Ribbon Untie & Reveal',
    videoDuration: '0:18',
    slots: [
      {
        id: 1,
        slotType: 'core',
        slotNumber: '1 of 7 (Main)',
        title: 'Hero Hamper Open Display',
        tagline: 'Amazon & Marketplace Compliant',
        badge: 'High CTR',
        categoryPurpose: 'Main Hamper Presentation',
        imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['All Items Visible Inside Box', 'Crisp White (#FFFFFF) Studio Ground', 'Satin Bow & Golden Foil Accent', 'Full Gift Set Staging'],
      },
      {
        id: 2,
        slotType: 'core',
        slotNumber: '2 of 7 (Infographic)',
        title: 'Complete "What’s Inside" Breakdown',
        tagline: 'Full Inventory with Callout Arrows',
        badge: 'Transparency',
        categoryPurpose: 'Itemized Value Explainer',
        imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Numbered Item Callouts', 'Grammage & Net Quantities', 'Artisan Treats + Scented Candle', 'Keepsake Reusable Rigid Box'],
      },
      {
        id: 3,
        slotType: 'core',
        slotNumber: '3 of 7 (Packaging)',
        title: 'Luxury Keepsake Gift Box & Ribbon',
        tagline: 'Premium Unboxing Aesthetic',
        badge: 'Gifting Appeal',
        categoryPurpose: 'Packaging Value Proof',
        imageUrl: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Rigid Magnetic Closure Box', 'Embossed Gold Foil Logo', 'Crinkle Paper Nesting', 'Luxury Satin Ribbon Bow'],
      },
      {
        id: 4,
        slotType: 'core',
        slotNumber: '4 of 7 (Lifestyle)',
        title: 'Festive & Celebration Lifestyle',
        tagline: 'Diwali, Wedding & Holiday Ambiance',
        badge: 'Emotional',
        categoryPurpose: 'Festive Table Setting',
        imageUrl: 'https://images.unsplash.com/photo-1513297887119-d46091b24bfa?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Warm Festive Fairy Lights', 'Celebration Dining Table Staging', 'Warm Joyful Tone', 'Gift Giving Context'],
      },
      {
        id: 5,
        slotType: 'core',
        slotNumber: '5 of 7 (Lifestyle)',
        title: 'Executive & Corporate Gifting',
        tagline: 'B2B Client & Employee Appreciation',
        badge: 'Corporate B2B',
        categoryPurpose: 'Professional Gifting Scene',
        imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Clean Modern Office Desk', 'High-End Leather & Laptop Backdrop', 'Sophisticated Neutral Palette', 'Bulk Order Friendly Callout'],
      },
      {
        id: 6,
        slotType: 'core',
        slotNumber: '6 of 7 (Macro Detail)',
        title: 'Artisan Ingredients & Freshness Macro',
        tagline: 'Quality Seal & Organic Certifications',
        badge: 'Safety & Quality',
        categoryPurpose: 'Sensory Detail Close-Up',
        imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Gourmet Chocolate / Nut Texture', 'FSSAI / Organic Seal Badges', 'No Preservatives Guarantee', 'Sealed Freshness Lock'],
      },
      {
        id: 7,
        slotType: 'core',
        slotNumber: '7 of 7 (Personalization)',
        title: 'Custom Message Card & Wax Seal',
        tagline: 'Personalized Gifting Touch',
        badge: 'Emotional Hook',
        categoryPurpose: 'Customization Proof',
        imageUrl: 'https://images.unsplash.com/photo-1579208575657-c595a05383b7?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Calligraphy Font Custom Note', 'Metallic Gold Wax Seal Option', 'Envelope Inside Hamper Lid', '100% Custom Greetings'],
      },
      {
        id: 8,
        slotType: 'plus2',
        slotNumber: '+1 of 2 (A+ Upgrade)',
        title: 'Handcrafted Artisan Sourcing Story',
        tagline: 'Connects Buyer to the Makers',
        badge: 'A+ Content',
        categoryPurpose: 'Brand Narrative Module',
        imageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Direct Artisan Collaboration', 'Fair Trade & Sustainable Pack', 'Small-Batch Hand Poured', 'Authentic Heritage Roots'],
      },
      {
        id: 9,
        slotType: 'plus2',
        slotNumber: '+2 of 2 (A+ Upgrade)',
        title: 'Multi-Occasion Suitability Guide',
        tagline: 'One Box Solves 6 Gifting Occasions',
        badge: 'A+ Content',
        categoryPurpose: 'Universal Use-Case Grid',
        imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Birthday & Anniversary Icons', 'Diwali / Holiday Season Icons', 'Corporate Thank You Icon', 'Housewarming & Wedding Favor'],
      },
    ],
  },
  {
    id: 'artisan',
    name: 'Artisan Crafts & Home Decor',
    subtitle: 'Ceramics, brassware, textiles & handcrafted goods',
    description: 'The 7+2+1 visual engine for Indian handicrafts and artisan brands selling on Etsy, Amazon Global Selling, and Shopify.',
    badge: 'Artisan Heritage',
    videoUrl: '/src/assets/portfolio-5.mp4',
    videoPoster: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    videoTitle: 'Artisan Wheel & Texture In-Motion',
    videoDuration: '0:20',
    slots: [
      {
        id: 1,
        slotType: 'core',
        slotNumber: '1 of 7 (Main)',
        title: 'Artisan Pure White Hero',
        tagline: 'Amazon & Etsy Search Ready',
        badge: 'Hero Image',
        categoryPurpose: 'Clear Silhouette & Shadows',
        imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Crisp Pure White Ground', 'Authentic Natural Glaze Color', 'True-to-Life Proportions', 'Handmade Character Visible'],
      },
      {
        id: 2,
        slotType: 'core',
        slotNumber: '2 of 7 (Infographic)',
        title: 'Dimensions & Capacity Scale',
        tagline: 'Prevents "Smaller Than Expected" Reviews',
        badge: 'Clarity',
        categoryPurpose: 'Visual Scale Guide',
        imageUrl: 'https://images.unsplash.com/photo-1615486511484-92e172cc4fe0?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Height, Diameter & Volume', 'Holding in Hand Scale Shot', 'Oven/Dishwasher Safe Badges', 'Gram Weight Indicator'],
      },
      {
        id: 3,
        slotType: 'core',
        slotNumber: '3 of 7 (Craftsmanship)',
        title: 'Raw Earth & Wheel Crafting Callouts',
        tagline: 'Celebrates Natural Clay & Kiln Fire',
        badge: 'Authenticity',
        categoryPurpose: 'Artisan Craftsmanship Proof',
        imageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['100% Natural Terracotta/Clay', '1200°C High-Fired Strength', 'Lead-Free Non-Toxic Glaze', 'No Two Pieces Are Identical'],
      },
      {
        id: 4,
        slotType: 'core',
        slotNumber: '4 of 7 (Lifestyle)',
        title: 'Warm Tabletop Styling',
        tagline: 'Shows Product in Daily Morning Routine',
        badge: 'Lifestyle Hero',
        categoryPurpose: 'Dining Context',
        imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Morning Coffee / Tea Steam', 'Linen Napkin & Wooden Table', 'Warm Natural Sunlight', 'Inviting Sensory Aesthetic'],
      },
      {
        id: 5,
        slotType: 'core',
        slotNumber: '5 of 7 (Lifestyle)',
        title: 'Open Kitchen / Shelf Display',
        tagline: 'Shows Collection as Home Decor',
        badge: 'Versatile',
        categoryPurpose: 'Home Decor Context',
        imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Open Floating Shelves', 'Stacking & Storage Display', 'Neutral Architectural Palette', 'Modern Rustic Balance'],
      },
      {
        id: 6,
        slotType: 'core',
        slotNumber: '6 of 7 (Macro Detail)',
        title: 'Macro Glaze Texture & Rim Detail',
        tagline: 'Proves Hand-Threw Tactile Finish',
        badge: 'Sensory Detail',
        categoryPurpose: 'High Zoom Inspection',
        imageUrl: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Organic Speckled Glaze', 'Smooth Lip Rim for Drinking', 'Thumb Indent Ergonomic Grip', 'Matte Clay Base Contrast'],
      },
      {
        id: 7,
        slotType: 'core',
        slotNumber: '7 of 7 (Packaging)',
        title: 'Drop-Tested Ceramic Packaging',
        tagline: 'Guaranteed Transit Protection',
        badge: 'Zero Broken Items',
        categoryPurpose: 'Safe Shipping Reassurance',
        imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Custom Molded Honeycomb / Foam', '5-Ply Corrugated Shipping Box', 'Eco-Friendly Biodegradable Fill', '100% Free Replacement Pledge'],
      },
      {
        id: 8,
        slotType: 'plus2',
        slotNumber: '+1 of 2 (A+ Upgrade)',
        title: 'Artisan Heritage & Pottery Village Story',
        tagline: 'Empowering Indian Rural Craft Guilds',
        badge: 'A+ Content',
        categoryPurpose: 'Impact & Heritage Narrative',
        imageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Generations of Clay Tradition', 'Direct Fair-Wage Impact', 'Zero Industrial Waste', 'Handmade Stamp of Origin'],
      },
      {
        id: 9,
        slotType: 'plus2',
        slotNumber: '+2 of 2 (A+ Upgrade)',
        title: 'Handmade Clay vs Factory Ceramic Chart',
        tagline: 'Why Natural Pottery Tastes & Feels Better',
        badge: 'A+ Content',
        categoryPurpose: 'Comparison Table',
        imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
        dimensions: '2000 × 2000 px',
        aspectRatio: '1:1',
        keyElements: ['Retains Heat Naturally', '100% Chemical-Free Surface', 'Unique One-of-a-Kind Art', 'Biodegradable Lifecycle'],
      },
    ],
  },
];
