// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syoungrummuurrptckbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5b3VuZ3J1bW11dXJycHRja2J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTc5NjMsImV4cCI6MjA3NDM5Mzk2M30.a8elGRTGB92Jni3W-pkKLSH7eSEYSEQOqOpxx_HEIa4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});